### ISSUE TITLE
extern "C" is not closed in driver/usbfs/src/plib_usbfs.h

### ISSUE THREAD

**Issue by Psy-Kai** [Microchip-MPLAB-Harmony/usb#15]
The closing brace for the `extern "C" {` is missing in `driver/usbfs/src/plib_usbfs.h`.

**Comment by pustekuchen91** [comment]
@shijas-mayan is this issue fixed with the next release?

**Comment by Psy-Kai** [comment]
On the current master branch this issue is still not fixed: https://github.com/Microchip-MPLAB-Harmony/usb/blob/172fdd3b504aa17cf341120e08002b5e6e07b656/driver/usbfs/src/plib_usbfs.h#L399

**Comment by shijas-mayan** [comment]
> On the current master branch this issue is still not fixed:
> 
> https://github.com/Microchip-MPLAB-Harmony/usb/blob/172fdd3b504aa17cf341120e08002b5e6e07b656/driver/usbfs/src/plib_usbfs.h#L399

This issue will be fixed in the next MPLAB Harmony USB release.

**Comment by shijas-mayan** [comment]
@Psy-Kai, This issue is resolved in USB v3.8.1.
